import '../models/task_model.dart';
import '../models/reward_model.dart';
import '../models/submission_model.dart';

class MockDataSeed {
  static List<TaskModel> get initialTasks {
    final now = DateTime.now();
    return [
      TaskModel(
        id: 'task_1',
        title: 'Morning Park & Trail Cleanup',
        description: 'Collect at least one bag of litter from your local neighborhood park or hiking trail.',
        detailedInstructions: '1. Grab a recyclable trash bag and gloves.\n2. Spend 20-30 minutes collecting litter along trails, picnic areas, or sports fields.\n3. Take a photo of the filled bag disposed in a public bin.\n4. Enable GPS verification to confirm you completed the task at a park.',
        bannerUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop',
        category: 'Eco & Green',
        pointsReward: 250,
        requiredSubmissions: [
          SubmissionType.photo,
          SubmissionType.text,
          SubmissionType.location,
        ],
        startDate: now,
        deadline: now.add(const Duration(hours: 14)),
        isRecurring: true,
        recurrenceRule: 'daily',
        createdBy: 'admin',
        createdAt: now.subtract(const Duration(hours: 2)),
      ),
      TaskModel(
        id: 'task_2',
        title: '5,000 Morning Steps Challenge',
        description: 'Complete a brisk morning walk of 5,000+ steps to energize your day.',
        detailedInstructions: '1. Put on your running shoes and track your morning walk using any fitness tracker or smartwatch.\n2. Take a screenshot of your step count exceeding 5,000 steps.\n3. Write a short note describing your route and mood.',
        bannerUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&auto=format&fit=crop',
        category: 'Fitness & Health',
        pointsReward: 150,
        requiredSubmissions: [
          SubmissionType.photo,
          SubmissionType.text,
        ],
        startDate: now,
        deadline: now.add(const Duration(hours: 8)),
        isRecurring: true,
        recurrenceRule: 'daily',
        createdBy: 'admin',
        createdAt: now.subtract(const Duration(hours: 4)),
      ),
      TaskModel(
        id: 'task_3',
        title: 'Support a Local Coffee Shop',
        description: 'Order from a neighborhood small business coffee shop and leave a thoughtful review.',
        detailedInstructions: '1. Visit an independent local coffee shop or bakery.\n2. Snap a photo of your cup/pastry with the storefront or logo.\n3. Leave a positive 5-star Google review and paste the text link or screenshot here.\n4. Verify your location at the venue.',
        bannerUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop',
        category: 'Community',
        pointsReward: 180,
        requiredSubmissions: [
          SubmissionType.photo,
          SubmissionType.location,
          SubmissionType.text,
        ],
        startDate: now,
        deadline: now.add(const Duration(hours: 18)),
        isRecurring: false,
        createdBy: 'admin',
        createdAt: now.subtract(const Duration(hours: 1)),
      ),
      TaskModel(
        id: 'task_4',
        title: 'Read 25 Pages & Share Top Takeaway',
        description: 'Dedicate 30 minutes to reading a non-fiction or educational book today.',
        detailedInstructions: '1. Choose a book focused on science, business, personal growth, or history.\n2. Read at least 25 pages without digital distractions.\n3. Take a photo of the book open to your favorite passage.\n4. Write down a 2-3 sentence summary of the key insight you learned.',
        bannerUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop',
        category: 'Learning',
        pointsReward: 120,
        requiredSubmissions: [
          SubmissionType.photo,
          SubmissionType.text,
        ],
        startDate: now,
        deadline: now.add(const Duration(hours: 22)),
        isRecurring: true,
        recurrenceRule: 'daily',
        createdBy: 'admin',
        createdAt: now.subtract(const Duration(hours: 6)),
      ),
      TaskModel(
        id: 'task_5',
        title: 'Record a 30-Second Creativity Pitch',
        description: 'Share a short video pitch of a creative project, idea, or artistic work you are building.',
        detailedInstructions: '1. Set up your camera and record a concise 30-60 second video.\n2. Explain what you are creating, why it matters, and what inspired it.\n3. Upload the short video clip directly through the app.',
        bannerUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop',
        category: 'Creative',
        pointsReward: 300,
        requiredSubmissions: [
          SubmissionType.video,
          SubmissionType.text,
        ],
        startDate: now,
        deadline: now.add(const Duration(hours: 36)),
        isRecurring: false,
        createdBy: 'admin',
        createdAt: now.subtract(const Duration(hours: 3)),
      ),
      TaskModel(
        id: 'task_6',
        title: 'Hydration & Mindful Stretch Habit',
        description: 'Drink 2 liters of water and complete a 10-minute posture stretch routine.',
        detailedInstructions: '1. Ensure you drink 2L+ of water throughout the day.\n2. Complete a 10-minute shoulder and spine stretch.\n3. Share a short note on how your body feels.',
        bannerUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop',
        category: 'Daily Habit',
        pointsReward: 80,
        requiredSubmissions: [
          SubmissionType.text,
        ],
        startDate: now,
        deadline: now.add(const Duration(hours: 12)),
        isRecurring: true,
        recurrenceRule: 'daily',
        createdBy: 'admin',
        createdAt: now.subtract(const Duration(hours: 5)),
      ),
    ];
  }

  static List<RewardModel> get initialRewards {
    return [
      RewardModel(
        id: 'rew_1',
        title: '\$10 Artisan Coffee Voucher',
        description: 'Redeemable for your favorite brew or espresso beverage at any partner coffee outlet.',
        imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop',
        pointsCost: 350,
        stock: 25,
        category: 'Dining & Drinks',
      ),
      RewardModel(
        id: 'rew_2',
        title: '1-Day Premium Fitness Pass',
        description: 'Full day access to high-end gym facilities, sauna, and pool amenities.',
        imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop',
        pointsCost: 500,
        stock: 12,
        category: 'Health & Fitness',
      ),
      RewardModel(
        id: 'rew_3',
        title: '\$25 Amazon Gift Card',
        description: 'Digital gift card code delivered instantly to your registered email address.',
        imageUrl: 'https://images.unsplash.com/photo-1526178613552-2b45c6c302f0?w=600&auto=format&fit=crop',
        pointsCost: 900,
        stock: 8,
        category: 'Shopping',
      ),
      RewardModel(
        id: 'rew_4',
        title: 'Cinema Movie Ticket Voucher',
        description: 'Valid for one standard admission ticket to any movie of your choice.',
        imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=600&auto=format&fit=crop',
        pointsCost: 450,
        stock: 18,
        category: 'Entertainment',
      ),
      RewardModel(
        id: 'rew_5',
        title: 'Eco Reusable Water Bottle',
        description: 'Double-walled insulated stainless steel bottle to keep drinks cold for 24 hours.',
        imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop',
        pointsCost: 750,
        stock: 15,
        category: 'Eco Merchandise',
      ),
    ];
  }

  static List<SubmissionModel> get initialSubmissions {
    final now = DateTime.now();
    return [
      SubmissionModel(
        id: 'sub_1',
        taskId: 'task_2',
        taskTitle: '5,000 Morning Steps Challenge',
        pointsReward: 150,
        userId: 'demo_user_1',
        userName: 'Alex Johnson',
        userEmail: 'alex@example.com',
        submittedAt: now.subtract(const Duration(minutes: 45)),
        status: 'pending',
        textResponse: 'Walked through the botanical garden loop early this morning. Total 6,240 steps recorded on my Fitbit!',
        photoUrls: ['https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&auto=format&fit=crop'],
      ),
      SubmissionModel(
        id: 'sub_2',
        taskId: 'task_1',
        taskTitle: 'Morning Park & Trail Cleanup',
        pointsReward: 250,
        userId: 'demo_user_2',
        userName: 'Sarah Miller',
        userEmail: 'sarah@example.com',
        submittedAt: now.subtract(const Duration(hours: 3)),
        status: 'approved',
        textResponse: 'Cleaned up plastic bottles and snack wrappers near the children playground.',
        photoUrls: ['https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop'],
        locationAddress: 'Victoria Park, Central Lawn',
        reviewedBy: 'Admin Team',
        reviewedAt: now.subtract(const Duration(hours: 1)),
      ),
      SubmissionModel(
        id: 'sub_3',
        taskId: 'task_4',
        taskTitle: 'Read 25 Pages & Share Top Takeaway',
        pointsReward: 120,
        userId: 'demo_user_1',
        userName: 'Alex Johnson',
        userEmail: 'alex@example.com',
        submittedAt: now.subtract(const Duration(days: 1)),
        status: 'rejected',
        rejectionReason: 'The uploaded photo was blurred and did not show the book page. Please retake a clear photo and resubmit!',
        textResponse: 'Finished chapter 4 on atomic habits.',
        reviewedBy: 'Admin Team',
        reviewedAt: now.subtract(const Duration(hours: 20)),
      ),
    ];
  }
}
